[workspace]
resolver = "2"
members = [
  "Chapter01/data-types",
  "Chapter01/debug-me",
  "Chapter01/execution-flow",
  "Chapter01/hello-world",
  "Chapter01/pi-estimator",
  "Chapter01/rust-pilib",
  "Chapter01/sequences",
  "Chapter01/testing",
  "Chapter01/traits",
  "Chapter02/custom-iterators",
  "Chapter02/enums",
  "Chapter02/generics",
  "Chapter02/iteration",
  "Chapter02/lifetimes",
  "Chapter02/mut-sharing-ownership",
  "Chapter02/not-null",
  "Chapter02/pattern-matching",
  "Chapter02/sharing-ownership",
  "Chapter02/trait-bounds",
  "Chapter02/unsafe-ways",
  "Chapter03/cargo-hello",
  "Chapter03/custom-build",
  "Chapter03/external-deps",
  "Chapter03/hello_world",
  "Chapter03/my-workspace/a-lib",
  "Chapter03/my-workspace/a-project",
  "Chapter03/publish-crate",
  "Chapter04/actors",
  "Chapter04/async-await",
  "Chapter04/black-white",
  "Chapter04/channels",
  "Chapter04/child-processes",
  "Chapter04/concurrent-processing",
  "Chapter04/immutable-states",
  "Chapter04/multiple-threads",
  "Chapter04/simple-threads",
  "Chapter04/use-rayon",
  "Chapter05/custom-errors",
  "Chapter05/exceptional-results",
  "Chapter05/external-crates",
  "Chapter05/multiple-errors",
  "Chapter05/options-results",
  "Chapter05/panicking-responsibly",
  "Chapter05/resilient-programming",
  "Chapter05/seamless-errors",
  "Chapter06/code-generation",
  "Chapter06/custom-macros",
  "Chapter06/dry-macros",
  "Chapter06/macro-overloading",
  "Chapter06/matching",
  "Chapter06/parameter-ranges",
  "Chapter06/std-macros",
  "Chapter07/bindgen/rust-tinyexpr",
  "Chapter07/browser-rust/rust-digest",
  "Chapter08/advanced-orm",
  "Chapter08/api",
  "Chapter08/authentication",
  "Chapter08/html-templates",
  "Chapter08/json-handling",
  "Chapter08/orm",
  "Chapter08/static-web",
  "Chapter08/web-errors",
  "Chapter09/cross-compile",
  "Chapter09/i2cdevice-drivers",
  "Chapter09/reading-hardware",
  "Chapter10/command-line-args",
  "Chapter10/dynamic-data",
  "Chapter10/file-stuff",
  "Chapter10/filesystem",
  "Chapter10/logging",
  "Chapter10/pipes",
  "Chapter10/random-numbers",
  "Chapter10/regex",
  "Chapter10/rusty-ml",
  "Chapter10/sub-processes",
  "Chapter10/web-requests",
]
default-members = [
  "Chapter01/debug-me",
  "Chapter01/hello-world",
  "Chapter01/pi-estimator",
  "Chapter02/pattern-matching",
  "Chapter02/trait-bounds",
  "Chapter03/cargo-hello",
  "Chapter03/custom-build",
  "Chapter03/external-deps",
  "Chapter03/hello_world",
  "Chapter03/my-workspace/a-project",
  "Chapter04/actors",
  "Chapter04/async-await",
  "Chapter04/black-white",
  "Chapter04/channels",
  "Chapter04/child-processes",
  "Chapter04/immutable-states",
  "Chapter04/multiple-threads",
  "Chapter04/simple-threads",
  "Chapter05/custom-errors",
  "Chapter05/external-crates",
  "Chapter05/multiple-errors",
  "Chapter05/resilient-programming",
  "Chapter06/custom-macros",
  "Chapter06/std-macros",
  "Chapter07/bindgen/rust-tinyexpr",
  "Chapter08/advanced-orm",
  "Chapter08/api",
  "Chapter08/authentication",
  "Chapter08/html-templates",
  "Chapter08/json-handling",
  "Chapter08/orm",
  "Chapter08/static-web",
  "Chapter08/web-errors",
  "Chapter09/cross-compile",
  "Chapter09/i2cdevice-drivers",
  "Chapter09/reading-hardware",
  "Chapter10/command-line-args",
  "Chapter10/file-stuff",
  "Chapter10/filesystem",
  "Chapter10/logging",
  "Chapter10/pipes",
  "Chapter10/rusty-ml",
  "Chapter10/sub-processes",
  "Chapter10/web-requests",
]
